### ISSUE TITLE
Not able to install manually

### ISSUE THREAD

**Issue by articuluxe** [melisgl/color-theme-mgl#1]
etc/themes/color-theme-mgl.el:51:12:Warning: ‘error’ called with 1 args to
etc/themes/mgl-dark-theme.el:1:1:Error: Cannot open load file: No such file or directory, color-theme-mgl
etc/themes/mgl-light-theme.el:1:1:Error: Cannot open load file: No such file or directory, color-theme-mgl

When mgl-dark-theme.el tries to include color-theme-mgl, it can't find it.
I think the issue is that `locate-file` does not know what to do with the `custom-theme-directory` element of `custom-theme-load-path`.  i.e. `(locate-file "color-theme-mgl.el" custom-theme-load-path '("c" ""))` returns nil for me, even though "color-theme-mgl.el" IS present in my `custom-theme-directory`.

**Comment by melisgl** [comment]
Thank you for the report and the diagnosis. Fixed in 9d5465da7359cf630fe2113c09ec82ffb621d3c3.
